console.log(Boolean(123)); // true
console.log(Boolean(-123)); // true
console.log(Boolean(0)); // false
console.log(Boolean(NaN)); // false
console.log(Boolean(1n)); // true
console.log(Boolean(0n)); // false
console.log(Boolean('foo')); // true
console.log(Boolean('')); // false
console.log(Boolean(true)); // true
console.log(Boolean(false)); // false
console.log(Boolean(null)); // false
console.log(Boolean(undefined)); // false
console.log(Boolean({})); // true
